#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-domain_name
Version  : 0.5.20160615
Release  : 10
URL      : https://rubygems.org/downloads/domain_name-0.5.20160615.gem
Source0  : https://rubygems.org/downloads/domain_name-0.5.20160615.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.1 MPL-1.1
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-shoulda
BuildRequires : rubygem-test-unit

%description
domain_name
===========
Synopsis
--------
Domain Name manipulation library for Ruby

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n domain_name-0.5.20160615
gem spec %{SOURCE0} -l --ruby > rubygem-domain_name.gemspec

%build
gem build rubygem-domain_name.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
domain_name-0.5.20160615.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/domain_name-0.5.20160615.gem
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/.document
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/README.md
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/data/effective_tld_names.dat
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/domain_name.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/lib/domain_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/lib/domain_name/etld_data.rb
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/lib/domain_name/etld_data.rb.erb
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/lib/domain_name/punycode.rb
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/lib/domain_name/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/test/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/test/test_domain_name-punycode.rb
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/test/test_domain_name.rb
/usr/lib64/ruby/gems/2.3.0/gems/domain_name-0.5.20160615/tool/gen_etld_data.rb
/usr/lib64/ruby/gems/2.3.0/specifications/domain_name-0.5.20160615.gemspec
